import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "DxO Wiki  ",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-[#2c2c2c] text-3xl`}
      >
        <div className="flex flex-col h-screen  m-10 ">
          <Navbar/>
          <div className="pt-10 border-t ">
          {children}
          </div>
        </div>
       
      </body>
    </html>
  );
}
